### ISSUE TITLE
Osciloscope doesn't show anything

### ISSUE THREAD

**Issue by takuvata** [takuvata/org.freedesktop.LinuxAudio.Lv2Plugins.ZynFusion#3]
I am pretty sure it was working at some point.

**Comment by takuvata** [comment]
It works when sources for zynaddsubfx are pulled from master, not the last release (that's what https://github.com/zynaddsubfx/zyn-fusion-build/blob/master/build-linux.rb script also does). However, it's against Flathub's policy to build from master.

Problem may be the fact that while building release, sources for zest build are pulled from master and not from corresponding release. Reason for that is the fact that build tools in the release are performing bunch of git pulls, which is not allowed (and for good reasons) in Flatpak's build process.

**Comment by hfiguiere** [comment]
If you have a patch to get from git that fixes it, it is allowed to add that patch. But if it is broken in the release, it's also ok to be broken.

**Comment by takuvata** [comment]
Thing is - I am already building zest from the master, as release build  does perform bunch of git fetches and I just do not have the time to fix all that.

**Comment by takuvata** [comment]
actually that well may be the reason - zest and zyn  are not in sync.

**Comment by takuvata** [comment]
Anyway, for now pushed a new branch for builds from master, later maybe will take a look what can be done to sync the release sources and whether it was actually broken in the release.

**Comment by takuvata** [comment]
OK, it seems I figured it out: commit: https://github.com/mruby-zest/mruby-zest-build/commit/c6a0e97eb7658200287e47c28a63965b381ee581 changed build script to use submodules, but it was still 3.0.5 submodules and apparently in the release 3.0.5 they simply did not have the oscilloscope in the UI at all. Explains why it's not functional when sources are not in sync. Fixed git commit in manifest - I'd rather not have UI element at all then have broken one.

**Comment by takuvata** [comment]
Upside of the resent change is that both - built from my 'master' (so 3.0.5) and 'build-from-master' (git head) branches, plugins appears to be quite stable now - experienced no crashes after hours of trying to abuse them in all sorts of ways.
